language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.0

script:
- set -o pipefail
- xcodebuild test -enableCodeCoverage YES -workspace Example/SidePanelController.xcworkspace -scheme "SidePanelController-Example" -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty
